### ISSUE TITLE
New to python

### ISSUE THREAD

**Issue by DevKnight0** [SaiTeja69/Digital_Text_To_Handwriting#3]
Which api and topics do i have know about to understand your code?

**Comment by SaiTeja69** [comment]
Numpy and stacks.

**Comment by DevKnight0** [comment]
![15869862594701720128446182501725](https://user-images.githubusercontent.com/60839277/79391114-8ca61680-7f8e-11ea-89fd-26d368a9f661.jpg)
After adding more than 4 line pycharm shows this error

**Comment by Shivam0808** [comment]
same error

**Comment by DevKnight0** [comment]
Check my repo i have made it in java

**Comment by SaiTeja69** [comment]
Great 🔥 i have been busy lately and couldn't check it ! I will fix it soon
